### ISSUE TITLE
Installation issue with panda_simulator

### ISSUE THREAD

**Issue by zyq476916822** [justagist/panda_simulator#18]
As required, I git clone panda_simulator, franka_panda_description, franka_ros_interface and orocos_kinematics_dynamics from github web pages into my workspace. When I catkin_make my workspace, there's an error shown as below,

at /opt/ros/melodic/share/catkin/cmake/catkin_workspace.cmake:100 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:69 (catkin_workspace)

-- Configuring incomplete, errors occurred!
See also "/home/george/ws_franka/build/CMakeFiles/CMakeOutput.log".
See also "/home/george/ws_franka/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

I am not sure how to figure this out. Hopefully, this can be explained.

**Comment by justagist** [comment]
Please use `catkin build` instead of `catkin_make` to build your workspace. You might have to do a clean build if you used `catkin_make` before.
To ensure you are using the right versions of franka_ros_interface and orocos_kinematics_dynamics, use the `dependencies.rosinstall` file to clone the required packages (follow instructions in readme).
