### ISSUE TITLE
 I use cpp to imitate python script(move_robot.py). message md5sum is mismatch.

### ISSUE THREAD

**Issue by TracyLestrade** [justagist/panda_simulator#42]
I copied some .msg files from `franka_ros_interface\franka_common\franka_core_msgs\msg`  to my package(panda_sim_testcpp) `panda_sim_testcpp\msg`. 
and I change package.xml, CMakeList.txt to configure it.
it occured error. because it missed some dependencies. 
so, I copied `franka_ros\franka_msgs` this package to my catkin workspace.
it.  after that, I added package dependency.
`  
<build_depend>franka_msgs</build_depend>
  <exec_depend>franka_msgs</exec_depend>
`
now, compile successed. 
i quiet sure about my cpp code correct. and i ran my node get errors. goes with md5sum is mismatch.

[ERROR] [1619424870.047841513]: md5sum mismatch making local subscription to topic /panda_simulator/motion_controller/arm/joint_commands.
[ERROR] [1619424870.050563349]: Subscriber expects type sensor_msgs/JointState, md5sum 3066dcd76a6cfaef579bd0f34173e9fd
[ERROR] [1619424870.050673424]: Publisher provides type panda_sim_testcpp/JointCommand, md5sum 766f72e801d6180a86db23dbf2c2a56f

how can i generate right header.  could u give me some advice? I also want to know the right message md5.

**Comment by justagist** [comment]
You shouldn't have to copy the `msg` directories to your package. You should be able to use them directly in your package just by adding them as dependencies in your build configuration files. I believe the mismatch in the signatures could be because there are multiple instances of the same message files in your workspace.
Also, I will not be able to help you with building a different ROS package, sorry; please use other sources for figuring out these issues.
Closing this issue as it is not related to running or using this package. Please feel free to re-open if you think this wrong.

**Comment by TracyLestrade** [comment]
I checked.  the original md5 of _RobotState.py(franka_ros_interface) is same with mine. which it means the msg generation is fine. 
not multiple instances issue.
I guess there are some issue on my code. topic string I guess.
